cs_dust.wad
gfx/env/snowlake_bk.tga
gfx/env/snowlake_dn.tga
gfx/env/snowlake_ft.tga
gfx/env/snowlake_lf.tga
gfx/env/snowlake_rt.tga
gfx/env/snowlake_up.tga
halflife.wad
maps/aim_winter_challenge_btm.wad
maps/aim_snowy_winter.res
