//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/awp_india_winter.html
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardup.tga
sound/ambience/copter.wav
gfx/env/trainyardbk.tga
gfx/env/trainyardrt.tga
overviews/awp_india_winter.txt
overviews/awp_india_winter.bmp
sound/ambience/coldwind_1.wav
maps/awp_india_winter.bsp
maps/awp_india_winter.txt
