gfx/detail/dt_carpet1.tga
gfx/detail/dt_fabric2.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_stone4.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/detail/dt_wood.tga
gfx/env/infernobk.tga
gfx/env/infernodn.tga
gfx/env/infernoft.tga
gfx/env/infernolf.tga
gfx/env/infernort.tga
gfx/env/infernoup.tga
maps/de_inferno_nightcz.res
maps/de_inferno_nightcz.txt
maps/de_inferno_nightcz.txt
models/props/books1.mdl
models/props/bush_palmplant.mdl
models/props/bush_planter.mdl
models/props/cafe.mdl
models/props/couch_fabric-wreck.mdl
models/props/fan_ceiling.mdl
models/props/gondola.mdl
models/props/tree_brownv01.mdl
models/props/truck_large-brown.mdl
overviews/de_inferno_nightcz.bmp
overviews/de_inferno_nightcz.txt
czde_inferno.wad
hlbasics.wad
