//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_mirage_winter.html
sprites/flare1.spr
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
overviews/de_mirage_winter.txt
maps/de_mirage_winter.bsp
maps/de_mirage_winter.txt
