//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2013 - Infos @ http://www.17buddies.net //
//          More than 85000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by Chapo for 17Buddies.
//
// Map Name  : de_nuke_iarna
//
// Download @: http://www.17buddies.net/17b2/View/Map/52724/de_nuke_iarna.html
//
//////////////////////////////////////////////////////////
// Wad files legend:
//     *  : Hardcoded in bsp file, this wad was found (in
//          archive or on 17Buddies's website) but doesn't
//          contains any used texture.
//          However, this file may be necessary.
//     ** : Hardcoded in bsp file, this wad could not be
//          found (neither in archive nor on 17Buddies's
//          website) and thus could not be analysed.
//          However, this file may be necessary.
//////////////////////////////////////////////////////////
// de_nuke_1337.wad (**)
gfx/env/snowup.tga
gfx/env/snowdn.tga
gfx/env/snowlf.tga
gfx/env/snowrt.tga
gfx/env/snowft.tga
gfx/env/snowbk.tga
// sprites/flare1.spr
// sound/ambience/alienwind2.wav
