// de_pripyat.res - created by -SpawN- (Polikarpov Anton)
// Home Page http://cs-mapper.clan.su
// E-Mail cs-mapper2006@yandex.ru
// ICQ 295-145-073

// .res entries (72):
de_pripyat.wad
gfx/env/pripyat_up.tga
gfx/env/pripyat_dn.tga
gfx/env/pripyat_lf.tga
gfx/env/pripyat_rt.tga
gfx/env/pripyat_ft.tga
gfx/env/pripyat_bk.tga
models/spawn-lost/sp_topol.mdl
models/spawn-lost/sp_travka1.mdl
models/spawn-lost/sp_mycopka.mdl
models/spawn-lost/sp_lavka.mdl
models/spawn-lost/sp_bereza.mdl
models/spawn-lost/sp_vorona.mdl
models/spawn-lost/sp_pesok.mdl
models/spawn-lost/sp_derevo.mdl
models/spawn-lost/sp_lifterka.mdl
models/spawn-lost/sp_stolb.mdl
models/spawn-lost/sp_velik.mdl
models/spawn-lost/sp_dead_tv.mdl
models/spawn-lost/sp_matras.mdl
models/spawn-lost/sp_patron_linght.mdl
models/spawn-lost/sp_razvalins1.mdl
models/spawn-lost/sp_divan.mdl
models/spawn-lost/sp_shkaf.mdl
models/spawn-lost/sp_razvalins.mdl
models/spawn-lost/sp_garage.mdl
models/spawn-lost/sp_stul.mdl
models/spawn-lost/sp_batarea2.mdl
models/spawn-lost/sp_batarea1.mdl
models/spawn-lost/sp_parasha.mdl
models/spawn-lost/sp_telefon.mdl
models/spawn-lost/sp_budka.mdl
models/spawn-lost/sp_kyct.mdl
models/spawn-lost/sp_krovat.mdl
models/spawn-lost/sp_zapor.mdl
models/spawn-lost/sp_stol.mdl
models/spawn-lost/sp_patron.mdl
models/spawn-lost/sp_prypyat.mdl
sprites/pripyat/sp_list_2.spr
sprites/pripyat/sp_list_1.spr
sprites/pripyat/sp_cccp_2.spr
models/spawn-lost/sp_elektrovishka.mdl
models/spawn-lost/sp_gaz.mdl
models/spawn-lost/sp_skameika2.mdl
models/spawn-lost/sp_skameika1.mdl
models/spawn-lost/sp_shkaf1.mdl
models/spawn-lost/sp_cobaka.mdl
models/spawn-lost/sp_divan1.mdl
models/spawn-lost/sp_shkaf3.mdl
models/spawn-lost/sp_vaz.mdl
models/spawn-lost/sp_okowko02.mdl
models/spawn-lost/sp_okowko01.mdl
models/spawn-lost/sp_okowko03.mdl
models/spawn-lost/sp_okowko04.mdl
models/spawn-lost/sp_cveto4nica.mdl
models/spawn-lost/sp_morozilka.mdl
sound/de_pripyat/spawn/sp_kachela.wav
sound/de_pripyat/spawn/sp_vozduh.wav
sound/de_pripyat/spawn/sp_muha.wav
sound/de_pripyat/spawn/sp_shum.wav
sound/de_pripyat/spawn/sp_kust.wav
sound/de_pripyat/spawn/sp_gav.wav
sound/de_pripyat/spawn/sp_kap.wav
sound/de_pripyat/spawn/sp_voy.wav
models/spawn-lost/sp_dead_gaz.mdl
models/spawn-lost/sp_avtomat.mdl
models/spawn-lost/sp_urno.mdl
models/spawn-lost/sp_lampa_linght.mdl
sprites/pripyat/sp_glow.spr
overviews/de_pripyat.bmp
overviews/de_pripyat.txt
maps/de_pripyat.txt
maps/de_pripyat.res